name: libraryapp
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  fluttertoast: ^8.2.2



  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  http: ^1.3.0
  provider: ^6.1.4

  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
   - asset/book-stack.png
   - asset/khundew.png
   - asset/book2.png
   - asset/storytelling.png


