// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl96NJpW11C0gb3-bW173YowDcu7Cc33o',
    appId: '1:815049004188:web:5d93467eb6bbe4fbf78959',
    messagingSenderId: '815049004188',
    projectId: 'libraryapp-79da4',
    authDomain: 'libraryapp-79da4.firebaseapp.com',
    storageBucket: 'libraryapp-79da4.firebasestorage.app',
    measurementId: 'G-WVZPE4FRRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_RmOYmQs3Wr23Lg-7JANSRmNtV_FJOFI',
    appId: '1:815049004188:android:4d3cf971e41e9aa1f78959',
    messagingSenderId: '815049004188',
    projectId: 'libraryapp-79da4',
    storageBucket: 'libraryapp-79da4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl96NJpW11C0gb3-bW173YowDcu7Cc33o',
    appId: '1:815049004188:web:e2b2f2d34dbd16e0f78959',
    messagingSenderId: '815049004188',
    projectId: 'libraryapp-79da4',
    authDomain: 'libraryapp-79da4.firebaseapp.com',
    storageBucket: 'libraryapp-79da4.firebasestorage.app',
    measurementId: 'G-MJD9RVZ8H1',
  );
}
